spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch_repo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.springframework.batch: DEBUG
